[package]
name = "daikin-homekit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
clap = { version = "4.2.1", features = ["derive"] }
env_logger = "0.10.0"
form_urlencoded = "1.1.0"
futures = "0.3.28"
genawaiter = { version = "0.99.1", features = ["futures03"] }
hap = { git = "https://github.com/ewilken/hap-rs", tag = "v0.1.0-pre.15", version = "0.1.0-pre.15" }
hex = "0.4.3"
network-interface = "1.0.0"
reqwest = { version = "0.11.16", features = ["json"] }
retainer = "0.3.0"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serde_repr = "0.1.12"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"] }
