[package]
name = "daikin-homekit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
clap = { version = "4.2.1", features = ["derive"] }
form_urlencoded = "1.1.0"
hap = { git = "https://github.com/ewilken/hap-rs", tag = "v0.1.0-pre.15", version = "0.1.0-pre.15" }
hex = "0.4.3"
network-interface = "1.0.0"
reqwest = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["full"] }
