name: Release

on:
  push:
    tags: [ "v*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v3
      with:
        name: daikin-homekit_${{ matrix.os }}
        path: target/release/daikin-homekit

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
    - run: ls -R
    - run: |
        chmod +x daikin-homekit_macos-latest/daikin-homekit
        tar zcvf daikin-homekit_macos-latest.tar.gz daikin-homekit_macos-latest
        chmod +x daikin-homekit_ubuntu-latest/daikin-homekit
        tar zcvf daikin-homekit_ubuntu-latest.tar.gz daikin-homekit_ubuntu-latest
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          daikin-homekit_macos-latest.tar.gz
          daikin-homekit_ubuntu-latest.tar.gz
